import logging
from typing import Dict, Any, List
import networkx as nx
from langchain_core.messages import AIMessage
from langchain_core.runnables import RunnableConfig
import re

from .state import AgentState
from .database import get_user_node_timeline
from ..graph.ingestion import load_resilience_graph
from ..graph.retriever import retrieve_subgraph_context
from ..llm.engine import LLMEngine
from ..llm import prompts
from ..schemas.models import ExtractionOutput, AssessmentOutput, SafetyOutput

# Initialize module logger
logger = logging.getLogger(__name__)

# Initialize LLM Engine singleton and load graph into memory once
llm_engine: LLMEngine = LLMEngine()
resilience_graph: nx.DiGraph = load_resilience_graph()


def extractor_node(state: AgentState) -> Dict[str, Any]:
    """
    Analyzes the user's input message to extract active resilience nodes 
    using the Gemma LLM with structured output enforcement.

    Args:
        state (AgentState): Current state containing 'user_message'.

    Returns:
        Dict[str, Any]: Updated state dict with 'active_nodes'.
    """
    logger.info("[Extractor] Extractor Agent is analyzing input...")
    user_msg: str = state.get("user_message", "")
    
    extractor_chain = llm_engine.get_extractor_runner(prompts.EXTRACTOR_SYSTEM_PROMPT)
    result: ExtractionOutput = extractor_chain.invoke({"user_message": user_msg})
    signals_list: List[Dict[str, Any]] = [
        signal.model_dump() for signal in result.active_signals
    ]
    
    # Extract unique node IDs from active signals
    active_node_ids: List[str] = list({signal.node_id for signal in result.active_signals})
    logger.debug(f"[Extractor] Extracted {len(active_node_ids)} nodes and {len(signals_list)} signals.")
    
    return {"active_nodes": active_node_ids, "active_signals": signals_list}


def retriever_node(state: AgentState) -> Dict[str, Any]:
    """
    Retrieves formatted sub-graph context for active nodes from NetworkX.

    Args:
        state (AgentState): Current state containing 'active_nodes'.

    Returns:
        Dict[str, Any]: Updated state dict with 'subgraph_context'.
    """
    logger.info("[Retriever] Graph Retriever is fetching node knowledge...")
    active_nodes: List[str] = state.get("active_nodes", [])
    
    # Fetch structured string representation from NetworkX graph
    context: str = retrieve_subgraph_context(resilience_graph, active_nodes)
    logger.debug(f"[Retriever] Fetched subgraph context for nodes: {active_nodes}")
    
    return {"subgraph_context": context}


def calculate_composite_confidence(
    raw_confidence: float,
    status: str,
    signal_polarity: str,
    evidence_text: str
) -> float:
    """
    Calculates a calibrated composite confidence score to mitigate LLM overconfidence bias.

    This function evaluates the reliability of the Assessor's output by combining the LLM's 
    self-reported confidence with deterministic heuristic checks. It prevents brittle routing 
    in the multi-agent graph by enforcing strict logical consistency and evidence validation.

    The composite score is weighted as follows:
        - 30% LLM Self-Reported Confidence (`raw_confidence`)
        - 30% Evidence Density (Word count analysis of the exact extracted `evidence_text`)
        - 40% Logical Consistency (Alignment between Extractor's `signal_polarity` and Assessor's `status`)

    Args:
        raw_confidence (float): The self-reported confidence score generated by the LLM (0.0 to 1.0).
        status (str): The assigned resilience status by the Assessor ("GREEN", "YELLOW", "RED").
        signal_polarity (str): The emotional/situational polarity detected by the Extractor 
                               ("positive", "negative", "mixed").
        evidence_text (str): The exact phrase or substring extracted from the user's message.

    Returns:
        float: A calibrated confidence score bounded strictly between 0.0 and 1.0.
               If fatal contradictions are detected (e.g., RED status with 'positive' polarity), 
               the score is severely penalized to enforce disambiguation routing.
    """
    # 1. LLM Self-Reported Score (30%)
    llm_score = raw_confidence * 0.30

    # 2. Evidence Density Score (30%)
    # A solid evidence phrase typically has 3+ words.
    words = evidence_text.strip().split()
    if len(words) >= 4:
        evidence_score = 1.0
    elif len(words) > 0:
        evidence_score = len(words) / 4.0
    else:
        evidence_score = 0.0
    evidence_weight = evidence_score * 0.30

    # 3. Logical Consistency Score (40%)
    # Penalize contradictions (e.g., RED status but Extractor found 'positive' polarity)
    consistency_score = 0.5  # Neutral default
    status_upper = status.upper()
    polarity_lower = signal_polarity.lower()

    if status_upper == "RED" and polarity_lower == "negative":
        consistency_score = 1.0
    elif status_upper == "GREEN" and polarity_lower == "positive":
        consistency_score = 1.0
    elif status_upper == "YELLOW" and polarity_lower in ["mixed", "negative", "positive"]:
        consistency_score = 0.8
    elif status_upper == "RED" and polarity_lower == "positive":
        consistency_score = 0.0  # Fatal contradiction
    elif status_upper == "GREEN" and polarity_lower == "negative":
        consistency_score = 0.0  # Fatal contradiction

    consistency_weight = consistency_score * 0.40

    # Aggregate and cap at 1.0
    composite_score = llm_score + evidence_weight + consistency_weight
    final_conf = min(max(round(composite_score, 2), 0.0), 1.0)
    logger.debug(f"[Confidence] Calculated composite confidence: {final_conf} (raw: {raw_confidence})")
    return final_conf


def assessor_node(state: AgentState) -> Dict[str, Any]:
    """
    Evaluates resilience levels using extracted evidence and polarity signals,
    grounded in the retrieved subgraph context.

    Args:
        state (AgentState): Current state containing 'user_message', 
                            'subgraph_context', and 'active_signals'.

    Returns:
        Dict[str, Any]: Updated state with 'assessments' and 'requires_disambiguation'.
    """
    logger.info("[Assessor] Assessor Agent is evaluating resilience status with evidence...")
    user_msg: str = state.get("user_message", "")
    context: str = state.get("subgraph_context", "")
    active_signals: List[Dict[str, Any]] = state.get("active_signals", [])

    # 1. Format extracted signals & evidence substrings for prompt ingestion
    if active_signals:
        evidence_blocks = []
        for sig in active_signals:
            evidence_blocks.append(
                f"• Target Node: {sig.get('node_id')}\n"
                f"  - Extracted Polarity: {sig.get('detected_signal', 'mixed').upper()}\n"
                f"  - Exact User Substring (Evidence): \"{sig.get('evidence', '')}\""
            )
        formatted_evidence = "\n".join(evidence_blocks)
    else:
        logger.warning("[Assessor] No explicit extracted signals provided.")
        formatted_evidence = "No explicit extracted signals provided."

    # 2. Construct clear evidence-aware payload conforming to assessor.txt prompt
    enriched_input = (
        f"=== EXTRACTED SIGNALS & EVIDENCE ===\n"
        f"{formatted_evidence}\n\n"
        f"=== FULL USER MESSAGE ===\n"
        f"{user_msg}"
    )

    # 3. Invoke LLM chain with evidence payload
    assessor_chain = llm_engine.get_assessor_runner(prompts.ASSESSOR_SYSTEM_PROMPT)
    result: AssessmentOutput = assessor_chain.invoke({
        "user_message": enriched_input,
        "subgraph_context": context
    })
    
    # Create a quick lookup for active signals to match with assessments
    signal_lookup = {sig['node_id']: sig for sig in active_signals}
    
    requires_disambiguation_override = False
    assessments_list: List[Dict[str, Any]] = []

    # 4. Calibrate LLM confidence with heuristic multi-factor scoring
    for assessment in result.assessments:
        assessment_dict = assessment.model_dump()
        node_id = assessment_dict["node_id"]
        
        # Get corresponding signal data from Extractor
        signal_data = signal_lookup.get(node_id, {})
        signal_polarity = signal_data.get("detected_signal", "mixed")
        evidence_text = signal_data.get("evidence", "")

        # Recalculate true confidence
        true_confidence = calculate_composite_confidence(
            raw_confidence=assessment_dict["confidence"],
            status=assessment_dict["status"],
            signal_polarity=signal_polarity,
            evidence_text=evidence_text
        )
        
        # Override the LLM's self-reported confidence
        assessment_dict["confidence"] = true_confidence
        assessments_list.append(assessment_dict)

        # Re-evaluate routing logic based on the calibrated score
        if true_confidence < 0.70:
            logger.warning(f"[Assessor] Low confidence detected for node {node_id} ({true_confidence}). Flagging disambiguation.")
            requires_disambiguation_override = True

    return {
        "assessments": assessments_list,
        "requires_disambiguation": requires_disambiguation_override 
    }


def questioner_node(state: AgentState, config: RunnableConfig) -> Dict[str, Any]:
    """
    Generates a targeted, empathetic clarification question when input is ambiguous,
    using the full conversational memory.

    Args:
        state (AgentState): Current state with 'messages' and 'subgraph_context'.

    Returns:
        Dict[str, Any]: Updated state dict with 'final_response' and 'messages'.
    """
    logger.info("[Questioner] Questioner Agent is formulating clarification...")
    context: str = state.get("subgraph_context", "")
    
    # Fetch the full chat history from the graph state
    messages_history = state.get("messages", [])

    stream_handler = config.get("configurable", {}).get("stream_handler")
    conversational_llm = llm_engine.get_conversational_llm()
    prompt = prompts.get_questioner_prompt()
    chain = prompt | conversational_llm    
    question_text = ""
    for chunk in chain.stream({
        "user_message": state.get("user_message", ""),
        "subgraph_context": context,
        "messages": messages_history
    }):
        question_text += chunk.content
        if stream_handler:
            stream_handler.on_llm_new_token(chunk.content)

    logger.debug("[Questioner] Clarification question successfully streamed.")
    return {
        "final_response": question_text,
        "messages": [AIMessage(content=question_text)]
    }


def advisor_node(state: AgentState, config: RunnableConfig) -> Dict[str, Any]:
    """
    Generates tailored psychological advice and interventions using active graph guidance
    combined with the user's historical resilience profile and full conversational memory.

    Args:
        state (AgentState): Current state with 'user_id', 'messages', 'subgraph_context', and 'assessments'.

    Returns:
        Dict[str, Any]: Updated state dict with 'final_response' and 'messages'.
    """
    logger.info("[Advisor] Advisor Agent is generating psychological interventions with full memory...")
    user_id: int = state.get("user_id", 0)
    subgraph_context: str = state.get("subgraph_context", "")
    assessments: List[Dict[str, Any]] = state.get("assessments", [])
    
    # Fetch the full chat history from the graph state
    messages_history = state.get("messages", [])
    
    # Fetch user's historical resilience timeline from SQLite database
    history_logs: List[Dict[str, Any]] = get_user_node_timeline(user_id) if user_id else []
    
    # Format historical profile into a chronological timeline block
    history_context: str = "No prior historical timeline recorded."
    if history_logs:
        timeline_by_node = {}
        for log in history_logs:
            nid = log.get('node_id')
            if nid not in timeline_by_node:
                timeline_by_node[nid] = []
            
            date_str = str(log.get('created_at', ''))[:10]
            status = log.get('status', 'UNKNOWN')
            score = log.get('score', 'N/A')
            timeline_by_node[nid].append(f"[{date_str}] {status}({score})")
        
        formatted_logs = []
        for nid, timeline in timeline_by_node.items():
            path_str = " ➔ ".join(timeline)
            formatted_logs.append(f"• Node {nid} Timeline: {path_str}")
            
        history_context = "\n".join(formatted_logs)
        logger.debug(f"[Advisor] Loaded timeline history for user {user_id}.")
    
    # Combine real-time graph context with the user's historical profile
    full_context: str = (
        f"=== CURRENT GRAPH KNOWLEDGE ===\n{subgraph_context}\n\n"
        f"=== USER HISTORICAL RESILIENCE PROFILE ===\n{history_context}"
    )

    stream_handler = config.get("configurable", {}).get("stream_handler")
    conversational_llm = llm_engine.get_conversational_llm()
    prompt = prompts.get_advisor_prompt()
    chain = prompt | conversational_llm    
    advice_text = ""
    for chunk in chain.stream({
        "user_message": state.get("user_message", ""),
        "subgraph_context": full_context,
        "assessments": str(assessments),
        "messages": messages_history
    }):
        advice_text += chunk.content
        if stream_handler:
            stream_handler.on_llm_new_token(chunk.content)

    if not advice_text or not advice_text.strip():
        logger.error("[Advisor] LLM returned an empty response.")
        advice_text = "متأسفانه در پردازش پاسخ خطایی رخ داد. لطفاً صفحه را رفرش کرده یا نشست جدیدی آغاز کنید."
    else:
        logger.debug("[Advisor] Advice successfully streamed and generated.")
    
    return {
        "final_response": advice_text,
        "messages": [AIMessage(content=advice_text)]
    }


def normalize_persian_text(text: str) -> str:
    """
    Standardizes Persian text by unifying characters, removing diacritics, 
    punctuations, ZWNJ (\u200c), and normalizing whitespaces.
    """
    if not text:
        return ""

    # 1. Unified Arabic to Persian characters
    translation_table = str.maketrans({
        'ي': 'ی', 'ى': 'ی', 'ئ': 'ی',
        'ك': 'ک',
        'آ': 'ا', 'أ': 'ا', 'إ': 'ا',
        'ۀ': 'ه', 'ة': 'ه',
        '۰': '0', '۱': '1', '۲': '2', '۳': '3', '۴': '4',
        '۵': '5', '۶': '6', '۷': '7', '۸': '8', '۹': '9'
    })
    text = text.translate(translation_table)

    # 2. Remove Persian/Arabic diacritics (اعراب)
    text = re.sub(r'[\u064B-\u065F\u0670]', '', text)

    # 3. Replace ZWNJ (\u200c) and punctuation with space
    text = re.sub(r'[\u200c\u200d\r\n\t\f\v!?,.:;؛؟"\'()\-[\]{}<>/\\]', ' ', text)

    # 4. Collapse multiple spaces into a single space
    text = re.sub(r'\s+', ' ', text).strip()

    return text.lower()


def safety_classifier_node(state: AgentState) -> Dict[str, Any]:
    """
    Primary zero-tolerance safety gate.
    Pipeline: Raw Input -> Persian Normalization -> High-Recall Heuristic -> LLM Classifier -> Policy Router
    """
    logger.info("[Safety] Safety Gate is checking for high-risk signals...")
    user_msg: str = state.get("user_message", "")
    
    # 1. Text Normalization
    normalized_msg = normalize_persian_text(user_msg)
    
    # 2. Context-Aware Crisis Intent Phrases (High-Recall, Low-False-Positive)
    crisis_phrases = [
        "خودکشی",
        "خودمو بکشم",
        "خودم رو بکشم",
        "خودکشی کنم",
        "نمیخوام زنده باشم",
        "نمی خواهم زنده باشم",
        "میخوام بمیرم",
        "می خواهم بمیرم",
        "پایان بدم به زندگی",
        "پایان دادن به زندگی",
        "رگمو بزنم",
        "رگم رو بزنم",
        "رگم بزنم",
        "قصدم خودکشیه",
        "خسته شدم از زندگی میخوام بمیرم"
    ]

    # Check for multi-word phrases or explicit suicide intent
    if any(phrase in normalized_msg for phrase in crisis_phrases):
        logger.warning(f"[Safety] Fast heuristic triggered high-risk flag on normalized input.")
        return {
            "safety_status": "HIGH_RISK", 
            "safety_flag": True
        }
        
    # 3. LLM-based Safety Classification (Context-aware fallback)
    try:
        safety_chain: Any = llm_engine.get_safety_runner(prompts.SAFETY_CLASSIFIER_PROMPT)
        result: SafetyOutput = safety_chain.invoke({"user_message": user_msg})
        
        if result.is_high_risk:
            logger.warning(f"[Safety] LLM Safety Classifier flagged high-risk signal. Category: {result.risk_category}")
            return {
                "safety_status": "HIGH_RISK", 
                "safety_flag": True
            }
            
        logger.debug("[Safety] Input evaluated as SAFE.")
        return {
            "safety_status": "SAFE", 
            "safety_flag": False
        }
        
    except Exception as e:
        logger.error(f"[Safety] Safety LLM execution failed ({e}). Defaulting to SAFETY_UNAVAILABLE status.")
        return {
            "safety_status": "UNAVAILABLE", 
            "safety_flag": False
        }


def service_unavailable_node(state: AgentState) -> Dict[str, Any]:
    """
    Handles cases where the safety subsystem or LLM backend is unavailable, 
    preventing un-vetted processing while gracefully informing the user.

    Args:
        state (AgentState): The current state dictionary of the workflow.

    Returns:
        Dict[str, Any]: A state update dictionary containing the formatted service 
                        unavailable message and appended AI message history.
    """
    logger.error("[ServiceUnavailable] Pipeline halted: Safety subsystem is unavailable.")
    unavailable_text: str = (
        "⚠️ **The system is temporarily experiencing some issues with the safety assessment section.**\n\n"
        "For security reasons, it is not possible to continue the psychological analysis at this time. "
        "Please try again in a few minutes or contact the help desk if you need immediate support."
    )
    return {
        "final_response": unavailable_text,
        "messages": [AIMessage(content=unavailable_text)]
    }


def emergency_response_node(state: AgentState) -> Dict[str, Any]:
    """
    Generates a deterministic emergency intervention response with official crisis hotlines,
    bypassing LLM generation completely to avoid hallucinations or clinical risks.

    Args:
        state (AgentState): Current graph state.

    Returns:
        Dict[str, Any]: Updated state dict with 'final_response' and 'messages'.
    """
    logger.critical("[Emergency] 🚨 HIGH RISK DETECTED: Routing to Emergency Protocols!")
    
    # Load static, clinically approved crisis text directly from prompt configuration
    emergency_text: str = prompts.EMERGENCY_RESPONSE_TEMPLATE
    
    return {
        "final_response": emergency_text,
        "messages": [AIMessage(content=emergency_text)]
    }
