from typing import List, Dict, Any, Annotated, Literal
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    Represents the internal shared state of the LangGraph workflow.
    
    Data is passed and mutated through this TypedDict across all agent nodes 
    and conditional edge routers during execution.

    Attributes:
        user_id (int): Unique identifier of the user executing the session.
        user_message (str): Current raw input message provided by the user.
        safety_flag (bool): Flag indicating if high-risk emergency content was detected.
        active_nodes (List[str]): Unique Node IDs activated by the Extractor Agent.
        active_signals (List[Dict[str, Any]]): Detailed signal payloads (node_id, polarity, evidence).
        subgraph_context (str): Formatted NetworkX graph knowledge context for active nodes.
        assessments (List[Dict[str, Any]]): Calibrated resilience assessments produced by the Assessor Agent.
        requires_disambiguation (bool): Flag indicating if low confidence forces clarification routing.
        final_response (str): Terminal output string generated by Advisor, Questioner, or Emergency node.
        messages (Annotated[List[BaseMessage], add_messages]): Conversational message history managed 
            incrementally by LangGraph's reducer.
    """
    
    # 1. User Input & Session Metadata
    user_id: int
    user_message: str
    
    # 2. Safety Gate Classification
    safety_status: Literal["SAFE", "HIGH_RISK", "UNAVAILABLE"]
    safety_flag: bool
    
    # 3. Extractor Agent Outputs
    active_nodes: List[str]
    active_signals: List[Dict[str, Any]]
    
    # 4. Graph Retriever Output
    subgraph_context: str
    
    # 5. Assessor Agent Outputs
    assessments: List[Dict[str, Any]]
    requires_disambiguation: bool
    
    # 6. Final Terminal Output
    final_response: str

    # 7. Conversational History (Managed incrementally by LangGraph reducer)
    messages: Annotated[List[BaseMessage], add_messages]
